package blog.anirbanm.viewsource.model.applicationModule.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 25 21:49:32 IST 2019
// ---------------------------------------------------------------------
public interface SourceDemoModule extends ApplicationModule {
    Row findByKey(String keyAttr1, String keyAttr2);
}

