package blog.anirbanm.viewsource.model.applicationModule;

import blog.anirbanm.viewsource.model.applicationModule.common.SourceDemoModule;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 25 21:45:51 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SourceDemoModuleImpl extends ApplicationModuleImpl implements SourceDemoModule {
    /**
     * This is the default constructor (do not remove).
     */
    public SourceDemoModuleImpl() {
    }
    
    public Row findByKey(final String keyAttr1, final String keyAttr2) {
        Row row = null;
        final ViewObjectImpl view = getSourceDemoVO1();
        // The sequence of the key attributes should be same as the View Object attributes.
        row = view.findByKey(new Key(new Object[] { keyAttr2, keyAttr1 }), 1)[0];
        System.out.println(":: selected row :: " + row);
        return row;
    }

    /**
     * Container's getter for SourceDemoVO1.
     * @return SourceDemoVO1
     */
    public ViewObjectImpl getSourceDemoVO1() {
        return (ViewObjectImpl) findViewObject("SourceDemoVO1");
    }
}

