CREATE TABLE VIEW_OBJECT_SOURCE_DEMO (
KEY_ATTR1 VARCHAR2(10),
KEY_ATTR2 VARCHAR2(10),
ATTRIBUTE1 VARCHAR2(256),
ATTRIBUTE2 VARCHAR2(256),
ATTRIBUTE3 VARCHAR2(256),
ATTRIBUTE4 VARCHAR2(256),
ATTRIBUTE5 VARCHAR2(256)
);

INSERT INTO VIEW_OBJECT_SOURCE_DEMO VALUES ('KEY1VALUE1', 'KEY2VALUE1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO VIEW_OBJECT_SOURCE_DEMO VALUES ('KEY1VALUE2', 'KEY2VALUE2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO VIEW_OBJECT_SOURCE_DEMO VALUES ('KEY1VALUE3', 'KEY2VALUE3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO VIEW_OBJECT_SOURCE_DEMO VALUES ('KEY1VALUE4', 'KEY2VALUE4', NULL, NULL, NULL, NULL, NULL);
INSERT INTO VIEW_OBJECT_SOURCE_DEMO VALUES ('KEY1VALUE5', 'KEY2VALUE5', NULL, NULL, NULL, NULL, NULL);

COMMIT;